name: Build website

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '5 4 * * *'

jobs:
  build:
    uses: ./.github/workflows/multiarch-build.yaml
    with:
      push_image: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}